-- ANEF Tracker Database Schema Export (SQLite 3.45)
-- Automatically generated by 'anef db schema export'

CREATE TABLE applications (
    id TEXT PRIMARY KEY,
    numero_demande TEXT NOT NULL,
    foreigner_id TEXT NOT NULL,
    legal_category TEXT,
    statut_code TEXT NOT NULL,
    statut_label TEXT NOT NULL,
    statut_description TEXT,
    site_retrait TEXT,
    version INTEGER NOT NULL DEFAULT 1,
    updated_at DATETIME NOT NULL
);

CREATE TABLE snapshot_meta (
    id TEXT PRIMARY KEY,
    timestamp DATETIME NOT NULL,
    directory TEXT NOT NULL,
    numero_demande TEXT NOT NULL,
    statut_code TEXT NOT NULL
);

CREATE TABLE events (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    snapshot_id TEXT NOT NULL,
    timestamp DATETIME NOT NULL,
    type TEXT NOT NULL,
    field_path TEXT NOT NULL,
    old_val TEXT,
    new_val TEXT,
    severity TEXT NOT NULL,
    confidence REAL NOT NULL
);

CREATE TABLE http_logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    method TEXT NOT NULL,
    url TEXT NOT NULL,
    request_headers TEXT,
    request_body TEXT,
    response_status INTEGER NOT NULL,
    response_body TEXT,
    timestamp DATETIME NOT NULL
);

CREATE TABLE evidence_records (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    source_type TEXT NOT NULL,
    snapshot_id TEXT,
    event_id INTEGER,
    http_log_id INTEGER,
    payload_hash TEXT NOT NULL,
    created_at DATETIME NOT NULL
);

CREATE TABLE retention_policy (
    resource TEXT PRIMARY KEY,
    keep_days INTEGER NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL
);
